# conda init && . ~/.bashrc && echo "conda init done"
# cp -r ./conda_env/faceclip /opt/conda/envs && echo "conda env copied"
# conda activate faceclip && echo "conda activated"
pip install face_alignment && echo "done1"
pip install seaborn && echo "done2"
pip install opencv-python==4.5.5.64 && echo "done3"
pip install openmesh && echo "done4"
pip install moviepy && echo "done5"
pip install dtw && echo "done 6"
apt-get install libosmesa6 && echo "done 7" 
pip install openai && echo "done 8"